// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoManuelController from "./auto_manuel_controller"
application.register("auto-manuel", AutoManuelController)

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModeNuitController from "./mode_nuit_controller"
application.register("mode-nuit", ModeNuitController)

import ReplaceShopProductController from "./replace_shop_product_controller"
application.register("replace-shop-product", ReplaceShopProductController)

import SearchProductsModalController from "./search_products_modal_controller"
application.register("search-products-modal", SearchProductsModalController)

import SortController from "./sort_controller"
application.register("sort", SortController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import VideoController from "./video_controller"
application.register("video", VideoController)
